/**
 * Scanner type definitions
 */

/**
 * Types of artifacts generated by the scanner
 */
export type ArtifactType =
    // Raw JSON artifacts from scanner
    | 'directory'
    | 'summary'
    | 'dataModel'
    | 'architecture'
    | 'workflow'
    // AI-generated markdown documentation
    | 'summary-docs'
    | 'dataModel-docs'
    | 'architecture-docs'
    | 'workflow-docs';

/**
 * Check if an artifact type is a documentation type
 */
export function isDocumentationArtifact(type: ArtifactType): boolean {
    return type.endsWith('-docs');
}

/**
 * Get the base artifact type for a documentation artifact
 */
export function getBaseArtifactType(type: ArtifactType): ArtifactType | null {
    if (type.endsWith('-docs')) {
        return type.replace('-docs', '') as ArtifactType;
    }
    return null;
}

/**
 * Configuration options for scanning
 */
export interface ScanOptions {
    excludePatterns?: string[];
    maxDepth?: number;
    skipLLMFallback?: boolean;
    maxFileSize?: number; // bytes, default 10MB
    /** Enable AI-powered documentation generation */
    generateDocumentation?: boolean;
    /** API endpoint for documentation generation */
    documentationApiEndpoint?: string;
}

/**
 * Default scan options
 */
export const DEFAULT_SCAN_OPTIONS: Required<ScanOptions> = {
    excludePatterns: ['node_modules', '.git', 'dist', 'build', '.next', 'out', 'coverage'],
    maxDepth: 3,
    skipLLMFallback: false,
    maxFileSize: 10 * 1024 * 1024, // 10MB
    generateDocumentation: false,
    documentationApiEndpoint: 'http://localhost:3000/api/ai-documentation'
};

/**
 * Error details from scanning
 */
export interface ScanError {
    stage: ArtifactType | 'init';
    message: string;
    filePath?: string;
}

/**
 * Result of generating a single artifact
 */
export interface ArtifactResult {
    type: ArtifactType;
    content: string; // JSON string or markdown
    generatedAt: string; // ISO8601
    fileCount: number;
    errorCount: number;
    incomplete?: boolean;
}

/**
 * Full scan result with all artifacts
 */
export interface ScanResult {
    artifacts: Partial<Record<ArtifactType, ArtifactResult>>;
    duration: number; // milliseconds
    errors: ScanError[];
    cancelled?: boolean;
}

/**
 * Progress callback signature for scan updates
 */
export type ProgressCallback = (stage: string, progress: number, message?: string) => void;

/**
 * Binary file extensions to skip during scanning
 */
export const BINARY_EXTENSIONS = new Set([
    // Images
    '.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', '.webp', '.bmp', '.tiff',
    // Documents
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
    // Archives
    '.zip', '.tar', '.gz', '.rar', '.7z', '.bz2',
    // Executables
    '.exe', '.dll', '.so', '.dylib', '.bin',
    // Fonts
    '.woff', '.woff2', '.ttf', '.eot', '.otf',
    // Media
    '.mp3', '.mp4', '.wav', '.avi', '.mov', '.mkv', '.flac', '.ogg',
    // Data
    '.dat', '.db', '.sqlite', '.sqlite3',
    // Lock files (binary)
    '.lock'
]);
